
[project]
name = "sierralobo-circuitpython-iam20380"
description = "gyroscope sensor library"
version = "0.0.0+auto.0"
readme = "README.md"
authors = [
    {name = "Caden Hillis"}
]

[project.urls]
Homepage = "https://github.com/Sierra-Lobo/Adafruit_CircuitPython_IAM20380"
